[package]
name = "raw_input"
version = "0.1.0"
edition = "2021"

[[test]]
name = "main_thread_tests"
path = "main_thread_tests/main.rs"
harness = false

[dependencies]
logwise = "0.2.1"

# macos
[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = "1.0.7"

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { version = "1.0.7", features = ["build"] }